### ISSUE TITLE
Does the native layer ever need to invoke functions on the webpage?

### ISSUE THREAD

**Issue by alexanderedge** [guardian/mobile-apps-thrift#12]
Thanks to @maxspencer for raising the question.

We've got a couple of functions for inserting the epic. Could this use-case be achieved by the web page asking the native layer for the epic instead? Could we avoid the native layer ever having to call a function on the web page at all, removing the requirement for a Thrift client in the app and a Thrift server in the web page?

https://github.com/guardian/mobile-apps-thrift/blob/6208f042c004268815c42294ac753d22b943663f/thrift/webview.thrift#L10

**Comment by alexanderedge** [comment]
This would also remove the requirement for a "ready" function from the webpage to the native layer.

**Comment by maxspencer** [comment]
> This would also remove the requirement for a "ready" function from the webpage to the native layer.

Yes, it was that discussion that gave me the idea in the first place.

**Comment by davidfurey** [comment]
Makes sense to me.

**Comment by alexanderedge** [comment]
I've just been speaking with @davidfurey about this, and he raised one scenario: scaling the text size. I don't see a way of achieving this without the native layer invoking functions on the web page.

**Comment by maxspencer** [comment]
Sorry to re-open this discussion, but for resizing text and anything similar can we not just follow the approach we use for toggling dark mode on/off: re-loading the view?

**Comment by alexanderedge** [comment]
> Sorry to re-open this discussion, but for resizing text and anything similar can we not just follow the approach we use for toggling dark mode on/off: re-loading the view?

We'd need to test it to be sure, but a concern I'd have is the user experience of reloading when the user changes the text size using the slider. However, if we move the slider out of the article and either into the app settings or fall back to system settings, then I'm not sure it's a problem.

**Comment by maxspencer** [comment]
Fair point about the UX, it would be relatively clunky compared to calling into the JS, though there are other ways to mitigate that like you say.
