### ISSUE TITLE
Interface segregation

### ISSUE THREAD

**Issue by alexanderedge** [guardian/mobile-apps-thrift#13]
Originally raised in https://github.com/guardian/mobile-apps-thrift/pull/6#issuecomment-581331888

Is there a benefit in segregating functions into different services? I'm concerned that `Native` might grow to become a protocol containing a collection of disparate functions.

For example, we could have `TopicService` defined as:

```thrift
struct Topic {
 	1: required string id;
 }

 service TopicService {
     void follow(topic: Topic),
     void unfollow(topic: Topic),
     bool isFollowing(topic: Topic),
 }
```

Could this approach be manageable in the JS code? What would a call-site look like? As far as the app is concerned, we'd need to implement each service separately, but the implementer of the service needn't always be the `ArticleViewController`, which is what would be the case if we had a single service.

**Comment by alexanderedge** [comment]
Jamie W's reply: 

> True, they are all quite different functions right now. The TypeScript would open up two connections and look like this:
> 
> ```ts
> import { createAppClient } from './thrift/NativeConnection';
> import * as Native from 'mobile-apps-thrift-typescript/Native';
> import * as Topic from 'mobile-apps-thrift-typescript/Topic';
> 
> const nativeClient: Native.Client<void> = createAppClient<Native.Client>(Native.Client, 'buffered', 'compact');
> const topicClient: Topic.Client<void> = createAppClient<Topic.Client>(Topic.Client, 'buffered', 'compact');
> 
> topicClient.followTopic();
> 
> export { nativeClient, topicClient };
> ```
> 
> I'm going to merge these PRs to continue working on [guardian/apps-rendering#173](https://github.com/guardian/apps-rendering/pull/173) but we can refactor them into separate services if it's easier. Would be interested in hearing Android opinons @maxspencer @ChrisOwen101

**Comment by alexanderedge** [comment]
I appreciate that there are quite a few different discussions going on at the moment, but I'd be interested in hearing your thoughts @maxspencer, @ChrisOwen101, @davidfurey.

**Comment by davidfurey** [comment]
I think it makes a lot of sense to namespace the different functionality.  I previously thought that services could contain other services which seemed like a nice model, but on further reading that doesn't seem to be possible.

Thrift does have a multiplexed protocol which might be useful, although at first glance it looks like the existing implementation only includes the Client side of the multiplexed protocol.
Alternatively the multiplexing could be done by each service could having its own message handler?

**Comment by davidfurey** [comment]
The typescript client doesn't support the thrift multiplexed protocol either

**Comment by alexanderedge** [comment]
I come to the same conclusion. Unless I've missed something, our options are (in no particular order):

1. Continue with the monolithic service
1. Implement the missing Swift (and, I assume, Java) `MultiplexedProcessor` server and `TMultiplexedProtocol` client in TypeScript
1. Use a unique message name for each service, mapping 1:1 to a native processor / server for each service
1. Use the existing message name and attempt to parse the message with each processor type – brute force multiplexing!

**Comment by davidfurey** [comment]
Java has the MultiplexedProcessor afaik since it seems to be the canonical implementation

I don't think 4 is really an option!

**Comment by alexanderedge** [comment]
As much as it seems like a detour at this point, I believe that we will be grateful later on that we did the right thing on both the TypeScript and native sides by adopting the multiplexed system.

**Comment by maxspencer** [comment]
To keep things simple, how about option 1b which is: continue with monolithic service from Typescript's point of view, and don't worry about the multiplexed protocol etc, but at the native code level, break down the implementation of the offending monolithic `Handler` class into smaller sub-components.

e.g.

```kotlin
class Handler(val topicHandler: TopicHandler, val adHandler: AdHandler) {
    fun follow(topic: Topic) {
        topicHandler.follow(topic)
    }
    ...

    fun insertAd(ad: Ad) {
        adHandler.insertAd(ad)
    }
    ...
}
```

etc.

If it's helpful to the webview code to know about the separate services then that's different obviously.

**Comment by alexanderedge** [comment]
> To keep things simple, how about option 1b which is: continue with monolithic service from Typescript's point of view, and don't worry about the multiplexed protocol etc, but at the native code level, break down the implementation of the offending monolithic `Handler` class into smaller sub-components.
> 
> e.g.
> 
> ```kotlin
> class Handler(val topicHandler: TopicHandler, val adHandler: AdHandler) {
>     fun follow(topic: Topic) {
>         topicHandler.follow(topic)
>     }
>     ...
> 
>     fun insertAd(ad: Ad) {
>         adHandler.insertAd(ad)
>     }
>     ...
> }
> ```
> 
> etc.
> 
> If it's helpful to the webview code to know about the separate services then that's different obviously.

This seems like a reasonable stop-gap. So, we create our smaller interfaces on the native side until such time as we add multiplexing? Then we can remove `Handler` and interfaces once multiplexing support is added in TypeScript?

**Comment by davidfurey** [comment]
I'd like to move to option 2 or 3 before we release to production, so that we do not have to continue to support a legacy API.  Happy to use 1b to avoid blocking progress for now though.

**Comment by maxspencer** [comment]
Yeah, I wasn't necessarily thinking of still doing 2 or three afterwards, but 1b would be a fine checkpoint on the way to either of those anyway. I don't have a stong opinion on whether 2 or 3 would be worthwhile to be honest. I would be neat, but I wonder whether YAGNI?

**Comment by alexanderedge** [comment]
> Yeah, I wasn't necessarily thinking of still doing 2 or three afterwards, but 1b would be a fine checkpoint on the way to either of those anyway. I don't have a stong opinion on whether 2 or 3 would be worthwhile to be honest. I would be neat, but I wonder whether YAGNI?

The apps would benefit from progressing to 2. by:

* Removing the need for the `Handler` class, which will be acting as some kind of router with many dependencies
* Removing the app-defined `TopicHandler`, `AdHandler` and other protocols in favour of the Thrift defined protocols.

I'm not sure if we would gain anything on the TypeScript side.
